backend:
  name: git-gateway
  branch: prd

# Editorial Workflow (drafts)
publish_mode: editorial_workflow

# Media directory
media_folder: "src/u"
public_folder: "/u"

collections:
  - name: "news"
    label: "News"
    folder: "src/posts/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", hint: "Thumbnail [400px by 400px] displayed on home and news index" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
