backend:
  name: git-gateway
  branch: dev

# Editorial Workflow (drafts)
publish_mode: editorial_workflow

# Media directory
media_folder: "u"

collections:
  - name: "news"
    label: "News"
    folder: "src/posts/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "string" }
