backend:
  name: git-gateway
  branch: prd

# CMS branding
logo_url: https://www.tlicycling.com/assets/img/tlicycling-cms.png
site_url: https://www.tlicycling.com
display_url: https://tlicycling.com

# Editorial Workflow (drafts)
publish_mode: editorial_workflow

# Media directory
media_folder: "src/u"
public_folder: "/u"

collections:
  - name: "news"
    create: true
    editor:
      preview: false
    folder: "src/posts/"
    label: "News"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", hint: "Thumbnail [320px by 180px] displayed on home and news index", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
      - { label: "Body", name: "body", widget: "markdown" }
